apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
  
patches:
- path: analysis-patch.json
  target:
    group: argoproj.io
    kind: AnalysisTemplate
    name: cpu-usage-app
    version: v1alpha1
- path: ingress-patch.json
  target:
    group: networking.k8s.io
    kind: Ingress
    name: dwk-todo-app-ingress
    version: v1
- path: pv-patch.json
  target:
    kind: PersistentVolume
    name: todo-pv
    version: v1
- path: pvc-patch.json
  target:
    kind: PersistentVolumeClaim
    name: todo-claim
    version: v1
    
images:
- name: TODOAPP/IMAGE
  newName: desipeli/dwk-todo-app
  newTag: 1764d02cd8e73a0c6d4a7f81f02f273bae741090
