apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
  
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: AnalysisTemplate
      name: cpu-usage-app
    path: analysis-patch.json
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: dwk-todo-app-ingress
    path: ingress-patch.json
  - target:
      group: ""
      version: v1
      kind: PersistentVolume
      name: todo-pv
    path: pv-patch.json
  - target:
      group: ""
      version: v1
      kind: PersistentVolumeClaim
      name: todo-claim
    path: pvc-patch.json
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: todo-app
    path: deployment-patch.yaml
    
images:
- name: TODOAPP/IMAGE
  newName: desipeli/dwk-todo-app
  newTag: e9f7f66798af03a5e818e93550257c78dd5ba713
