apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage
spec:
  metrics:
  - name: cpu-usage
    provider:
      prometheus:
        query: sum(rate(container_cpu_usage_seconds_total{namespace="production"}[10m]))