apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
  
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: broadcaster
    path: deployment-patch.json
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: AnalysisTemplate
      name: cpu-usage-broadcaster
    path: analysis-patch.json

images:
- name: TODOBROADCASTER/IMAGE
  newName: desipeli/dwk-broadcaster
  newTag: testtag2
