apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./analysistemplate.yaml
  - ./deployment.yaml
  - ./ingress.yaml
  - ./service.yaml
images:
  - name: TODOBROADCASTER/IMAGE
    newName: desipeli/dwk-broadcaster:4.06