apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: broadcaster
spec:
  template:
    spec:
      containers:
        - name: broadcaster
          env:
            - name: ENV
              value: staging