apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  
patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: broadcaster
    path: deployment-patch.json
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: AnalysisTemplate
      name: cpu-usage
    path: analysis-patch.json

namePrefix: stag-

images:
  - name: TODOBROADCASTER/IMAGE
    newName: desipeli/dwk-broadcaster
    newTag: b1e49c600adb7793e8393394bfca88669354e81f