apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./../../base
patches:
  - path: deployment.yaml
  - path: analysistemplate.yaml

images:
  - name: TODOBROADCASTER/IMAGE
    newName: desipeli/dwk-broadcaster:4.06