apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
  
patches:
  - target:
      group: argoproj.io
      kind: Rollout
      name: broadcaster
      version: v1alpha1
    path: deployment-patch.json
  - target: 
      group: argoproj.io
      kind: AnalysisTemplate
      name: cpu-usage-broadcaster
      version: v1alpha1
    path: analysis-patch.json

images:
- name: TODOBROADCASTER/IMAGE
  newName: desipeli/dwk-broadcaster
  newTag: eddb75213a1d532bfd287003c2a654990a627809
