apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage-backend
spec:
  metrics:
  - name: cpu-usage-backend
    initialDelay: 2m
    successCondition: result[0] < 0.5
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1727-prometheus.prometheus.svc.cluster.local:9090
        query: sum(rate(container_cpu_usage_seconds_total{namespace="REPLACE_THIS"}[10m]))