apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dwk-todo-ingress
  namespace: staging
spec:
  rules:
  - http:
      paths:
      - path: /todos
        pathType: Prefix
        backend:
          service:
            name: todo-backend-svc
            port:
              number: 5678